In [ ]:
#importing packages
import requests
from bs4 import BeautifulSoup
import time
!pip install Ipython
from IPython.display import clear_output

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: Ipython in /usr/local/lib/python3.8/dist-packages (7.9.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.8/dist-packages (from Ipython) (4.4.2)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from Ipython) (2.0.10)
Collecting jedi>=0.10
  Downloading jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 20.2 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.8/dist-packages (from Ipython) (57.4.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.8/dist-packages (from Ipython) (0.2.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.8/dist-packages (from Ipython) (2.6.1)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.8/dist-packages (from Ipython) (5.7.1)
Requirement already satisfied: pexpect in /usr/local/lib/python3.8/dist-packages (from Ipython) (4.8.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.8/dist-packages (from Ipython) (0.7.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.8/dist-packages (from jedi>=0.10->Ipython) (0.8.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.8/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->Ipython) (0.2.6)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.8/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->Ipython) (1.15.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.8/dist-packages (from pexpect->Ipython) (0.7.0)
Installing collected packages: jedi
Successfully installed jedi-0.18.2

In [ ]:
# bring things together

#create your empty lists
House_description = []
Address_of_property = []
Agent_of_property = []
Add_update_date_of_property = []
Price_of_property = []
Number_of_rooms = []
Num_of_bathrooms = []
Num_of_toilets = []


#intialising
base_url = "https://www.privateproperty.com.ng/houses-for-sale/enugu?page="
for i in range(0,9):
  url = (base_url+str(i))

  #we are pausing for 3 seconds (to prevent jamming the website)
  time.sleep(3)

  #showing the page being scaped and clearing the pages
  print(f'scrapping info from page {i}')
  clear_output(wait = True)

  #getting url and storing it.
  response = requests.get(url)
  response = response.content
  soup = BeautifulSoup(response, 'html.parser')

  #get the container of all the houses
  container = soup.find('div', class_ = 'result-listings')

  #enter into container and find all the house info and store them
  house_info = container.find_all('div', class_ = 'similar-listings-info')
  house_info2 = container.find_all('div', class_ = 'similar-listings-price')

  #get specific house description from the house_info
  for house in house_info:
    house_information = house.find('h2')
    House_description.append(house_information.text)
  
  #get specific address of property
  for address in house_info:
    house_address = address.find("p", class_ = "listings-location")
    Address_of_property.append(house_address.get_text("n/", strip = True))
  
  #get specific agent of property
  for agent in house_info:
    house_agent = agent.find("img")
    Agent_of_property.append(house_agent.attrs["alt"])

  #get specific dates for addding and updating of property online
  for date in house_info:
    house_date = date.find('h5', class_="mt-0")
    Add_update_date_of_property.append(house_date.text)
  
  #get specific prices of property
  for price in house_info2:
    house_price = price.h4
    house_price = house_price.contents[3]
    Price_of_property.append(house_price.text)
  
  # get number of rooms per property
  for room in house_info2:
    num_rooms = room.find("ul", class_="property-benefit")
    num_rooms = num_rooms.li
    Number_of_rooms.append(num_rooms.get_text("n/", strip = True))

  # get number of bathrooms per property
  for item in house_info2:
    bathroom = item.contents[3]
    bathroom = bathroom.contents[3]
    Num_of_bathrooms.append(bathroom.get_text("n/", strip = True))

  # get number of toilets per property
  for item in house_info2:
    toilet = item.contents[3]
    toilet = toilet.contents[5]
    Num_of_toilets.append(toilet.get_text("n/", strip = True))

scrapping info from page 8

In [ ]:
import pandas as pd
# Calling DataFrame constructor after zipping
# both lists, with columns specified
house= ['Property_description', 'Address_of_property','Agent_of_property','Add_update_date_of_property',
                           'Price_of_property', 'Number_of_rooms', 'Num_of_bathrooms','Num_of_toilets']
df = pd.DataFrame(list(zip(House_description, Address_of_property,Agent_of_property,Add_update_date_of_property,
                           Price_of_property, Number_of_rooms, Num_of_bathrooms,Num_of_toilets)),
			columns = house)
df

,Property_description,Address_of_property,Agent_of_property,Add_update_date_of_property,Price_of_property,Number_of_rooms,Num_of_bathrooms,Num_of_toilets
0,Twin 6 Bedroom Twin Duplex For Sale @ Golf One...,"Golf One Estate, Old Gra, Enugu Enugu Suburb E...",Pius Anno,"Updated 18 Feb 2023, Added 11 Jan 2023","130,000,000",6,5,6
1,Newly Built 4 Bedroom Duplex In A Serene Neigh...,"Emene, Enugu Enugu Area Enugu",Iwuba Ifediora and Associates,"Updated 15 Feb 2023, Added 01 Nov 2022","80,000,000",4,4,5
2,Block Of Flat,Enugu Suburb Enugu Area Enugu,Iwuba Ifediora and Associates,"Updated 15 Feb 2023, Added 06 Jan 2023","120,000,000",3,1,1
3,Newly Built 4 Bedroom Duplex In A Serene Neigh...,"Spotters Lifestyle Estate, Centenary City. Enu...",Iwuba Ifediora and Associates,"Updated 15 Feb 2023, Added 06 Jan 2023","80,000,000",4,5,5
4,Spacious 8 Bedroom Duplex,"Trans Ekulu, Enugu Area Enugu",Iwuba Ifediora and Associates,"Updated 15 Feb 2023, Added 01 Dec 2022","55,000,000",8,10,10
...,...,...,...,...,...,...,...,...
179,3 Bedroom Bungalow For Sale In Enugu Suburb,"Sanni Abacha Street, G.r.a Phase 6, Trans Ekul...",Godwin Kalu & Co.,Added 13 Apr 2015,"15,000,000",3,4,
180,5 Bedroom Detached House For Sale In Enugu Suburb,"Republic, Independence Layout, Enugu Enugu Sub...",Godwin Kalu & Co.,Added 17 Feb 2015,"35,000,000",5,5,
181,4 Bedroom Duplex For Sale In Enugu Suburb,"Along Ugwogwo Opi Road, Nike Enugu Enugu Subur...",Nwokoma Nwankwo & Co.,Added 04 Feb 2015,"18,000,000",4,4,
182,6 Bedroom Detached House For Sale In Enugu Suburb,"00 Nza Street, Independence Layout Enugu Subur...",Godwin Kalu & Co.,Added 22 Jan 2015,"140,000,000",6,,
183,3 Bedroom Bungalow For Sale In Enugu Suburb,Sanni Abacha Street Enugu Suburb Enugu Area Enugu,Godwin Kalu & Co.,Added 06 Jan 2015,"15,000,000",3,2,

In [ ]:
df.to_csv('Real_estate_data.csv')